### ISSUE TITLE
What are the deliverables? Is there a strict set of files to be delivered?

### ISSUE THREAD

**Issue by Abhijit89Kumar** [Aries-IITD/INNOV8-2.0#1]

**Comment by Abhijit89Kumar** [comment]
@iamsecretlyflash @aarcee17

**Comment by iamsecretlyflash** [comment]
If you check the problem statement pdf, we have mentioned the submission instructions. Your submission must be a zip file containing all your codes and the result.csv file  for part 1 which contains your predictions. The rows of result.csv should correspond to those of test.csv. 

For part 2 you have to create at least a well documented report. Include this pdf in the submission zip file as well.

**Comment by Abhijit89Kumar** [comment]
Thanks
